"""SQLAlchemy ORM models: Doctor, Patient, Session.

Only three tables exist. The clinical report generated by the LLM is stored
directly on the Session (JSON-encoded text columns) rather than a 4th table.
"""
from datetime import datetime, timezone
from typing import List, Optional

from sqlalchemy import DateTime, ForeignKey, Integer, String, Text
from sqlalchemy.orm import Mapped, mapped_column, relationship

from .database import Base


def utcnow() -> datetime:
    return datetime.now(timezone.utc)


class Doctor(Base):
    __tablename__ = "doctor"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, index=True)
    username: Mapped[str] = mapped_column(String(150), unique=True, index=True, nullable=False)
    name: Mapped[str] = mapped_column(String(255), nullable=False)
    specialty: Mapped[Optional[str]] = mapped_column(String(255), nullable=True)
    hashed_password: Mapped[str] = mapped_column(String(255), nullable=False)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=utcnow)

    # One doctor -> many patients.
    patients: Mapped[List["Patient"]] = relationship(
        back_populates="doctor", cascade="all, delete-orphan"
    )


class Patient(Base):
    __tablename__ = "patient"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, index=True)
    # Public identifier used across the app and for patient login.
    phone: Mapped[str] = mapped_column(String(32), unique=True, index=True, nullable=False)
    name: Mapped[str] = mapped_column(String(255), nullable=False)
    date_of_birth: Mapped[Optional[str]] = mapped_column(String(32), nullable=True)
    gender: Mapped[Optional[str]] = mapped_column(String(32), nullable=True)
    # Optional: patients may log in too. Null => managed only by the doctor.
    hashed_password: Mapped[Optional[str]] = mapped_column(String(255), nullable=True)

    # A patient has exactly one doctor.
    doctor_id: Mapped[int] = mapped_column(ForeignKey("doctor.id"), nullable=False, index=True)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=utcnow)

    doctor: Mapped["Doctor"] = relationship(back_populates="patients")
    # One patient -> many sessions.
    sessions: Mapped[List["Session"]] = relationship(
        back_populates="patient", cascade="all, delete-orphan"
    )


class Session(Base):
    """One consultation / follow-up visit between a doctor and a patient.

    Holds the conversation transcript and the embedded clinical report.
    """

    __tablename__ = "session"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, index=True)
    title: Mapped[Optional[str]] = mapped_column(String(255), nullable=True)
    # Transcript of the conversation (speech-to-text handled elsewhere / later).
    transcript: Mapped[str] = mapped_column(Text, nullable=False)
    # Reserved for a future audio recording reference.
    audio_path: Mapped[Optional[str]] = mapped_column(String(512), nullable=True)
    occurred_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=utcnow)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=utcnow)

    # ---- Embedded clinical report ----
    # One of: "pending_key" | "generated" | "error"
    report_status: Mapped[str] = mapped_column(String(32), default="pending_key", nullable=False)
    summary: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    # The following list/dict fields are stored as JSON-encoded strings.
    symptoms: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    issues_discussed: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    diagnosis: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    action_steps: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    medications: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    follow_up: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    report_raw: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    report_error: Mapped[Optional[str]] = mapped_column(Text, nullable=True)

    # A session belongs to one patient; the doctor is derived via patient.doctor.
    patient_id: Mapped[int] = mapped_column(ForeignKey("patient.id"), nullable=False, index=True)

    patient: Mapped["Patient"] = relationship(back_populates="sessions")
